version: '3'
services:
  go-service:
    build: ../go-api
    ports:
      - "8080:8080"
    networks:
     - mynetwork
  web-page:
    build: ../web-app
    ports:
      - "3000:3000"
    depends_on:
      - go-service
    networks:
      - mynetwork
networks:
  mynetwork: